### ISSUE TITLE
45.74528835847731, 12.5516625

### ISSUE THREAD

**Issue by vekexasia** [Daplie/s2-geometry.js#1]
S2.latLngToKey not working with these coordinates -> 2/ is returned.

**Comment by Skeec** [comment]
for me it returns 2/032330223130111

**Comment by coolaj86** [comment]
@vekexasia use version v1.2.6. It returns the same values as `s2geometry-node`:

```
Lat/Lng = 45.74528835847731,12.5516625 (@vekexasia)
Quadkey
= 2/032330223130111
j 2/032330223130111 (5150248300359712768)
```

**Comment by vekexasia** [comment]
Hello,

you're right. I forgot to pass the values as an object and i was passing lat and lng as two separate parameters.

@coolaj86 I added you to hangout using your gmail. I'm in the process to add Typescript support for this repo but i lack some knowledge about how S2 actually works.

Are you willing to accept my Google Hangout invitation so that we could chat?
