### ISSUE TITLE
S2 is undefined when using with node-webkit/NWJS

### ISSUE THREAD

**Issue by cpainchaud** [Daplie/s2-geometry.js#13]
importing module in node-webkit will result in S2 module import to fail:

var S2 = require('xxxxx').S2;
S2.latLngToKey(xxxx); <--- shoot error undefined S2

I think it could be caused by the last line of this library :

('undefined' !== typeof window ? window : module.exports);

in node-webkit/nwjs , 'window' variable is set (like in a standard Chromium).

**Comment by coolaj86** [comment]
Want to PR a fix? I bet swapping it to check typeof module or exports instead of window will work.

This is also used in browsers and browser plugins.

How do you handle that problem with your own modules?

**Comment by cpainchaud** [comment]
yes i fixed by forcing type.

concerning your request about how I handle that usually ... I never had to do such a module so I don't know :)

**Comment by coolaj86** [comment]
v1.2.8 is yours for the testing
