### ISSUE TITLE
Help Wanted: Implement S2.quadkeyToPoint(key) and S2.quadkeyToLatLng(key)

### ISSUE THREAD

**Issue by coolaj86** [Daplie/s2-geometry.js#4]
We can now finally convert between S2CellId (uint64) and Hilbert Quadkey.

See

* http://stackoverflow.com/a/38625109/151312
* https://github.com/jonatkins/s2-geometry-javascript/issues/9

However, we lack the support to go from from a key to lat / lng. It seems that once `this.ij` and `this.st` are calculated, we already know `this.face` (from either the key or id), so we can call the lat / lng method. However, we need to get those from the key/id somehow...

**Comment by coolaj86** [comment]
Probably useful

* https://github.com/golang/geo/blob/master/s2/latlng.go
* https://github.com/golang/geo/blob/master/s2/latlng_test.go

Alos may be helpful:

* https://github.com/golang/geo/blob/master/s2/cellid.go
* https://github.com/golang/geo/blob/master/s2/stuv.go

**Comment by lopper** [comment]
I have a pull request pending with Quadkey to s2Cell implemented. From s2Cell you can get the latLng.

**Comment by coolaj86** [comment]
Closed with #16. Much thanks @lopper

**Comment by coolaj86** [comment]
Published as v1.2.9
